New changes
Signed-off-by: Owais Kazi <owaiskazi19@gmail.com>

diff --git a/.github/workflows/check.yml b/.github/workflows/check.yml
--- a/.github/workflows/check.yml
+++ b/.github/workflows/check.yml
@@ -4,27 +4,41 @@ on: [pull_request]
 jobs:
   check:
     runs-on: ubuntu-latest
-    strategy:
-      matrix:
-        java: ['8', '11', '14', '17']
     env:
-      JAVA_HOME: /usr/lib/jvm/adoptopenjdk-14-hotspot-amd64
-      JAVA11_HOME: /usr/lib/jvm/adoptopenjdk-11-hotspot-amd64
-      JAVA8_HOME: /usr/lib/jvm/adoptopenjdk-8-hotspot-amd64
-      JAVA14_HOME: /usr/lib/jvm/adoptopenjdk-14-hotspot-amd64
-      JAVA17_HOME: /usr/lib/jvm/adoptopenjdk-17-hotspot-amd64
-
-    name: Java ${{ matrix.Java }} sample
+      JAVA_HOME: /opt/hostedtoolcache/Java_Adopt_jdk/14.0.2-12/x64/
+      JAVA11_HOME: /opt/hostedtoolcache/Java_Adopt_jdk/11.0.11-9/x64/
+      JAVA8_HOME: /opt/hostedtoolcache/Java_Adopt_jdk/8.0.292-1/x64/
+      JAVA14_HOME: /opt/hostedtoolcache/Java_Adopt_jdk/14.0.2-12/x64/
+      JAVA17_HOME: /opt/hostedtoolcache/Java_Adopt_jdk/17.0.1-12/x64/
     steps:
-      # - name: Checkout OpenSearch 
-      #   uses: actions/checkout@v2
+      - name: Checkout OpenSearch 
+        uses: actions/checkout@v2
 
       - uses: actions/checkout@v2
-      - name: Setup java
-        uses: actions/setup-java@v2
+      - uses: actions/setup-java@v2
         with:
           distribution: 'adopt'
-          java-version: ${{ matrix.java }}
+          java-version: '8'
+          targets: 'JDK_8'
+      - uses: actions/checkout@v2
+      - uses: actions/setup-java@v2
+        with:
+          distribution: 'adopt'
+          java-version: '11'
+          targets: 'JDK_11'
+      - uses: actions/checkout@v2
+      - uses: actions/setup-java@v2
+        with:
+          distribution: 'adopt'
+          java-version: '17'
+          targets: 'JDK_17'
+      - uses: actions/checkout@v2
+      - uses: actions/setup-java@v2
+        with:
+          distribution: 'adopt'
+          java-version: '14'
+          targets: 'JDK_14'
+      
     
 
       # - uses: AdoptOpenJDK/install-jdk@v1
@@ -52,18 +66,19 @@ jobs:
       - name: Print jdk
         run: |
           echo "PRINT HERE"
-          ls -l /usr/lib/jvm/
+          ls /opt/hostedtoolcache/Java_Adopt_jdk/14.0.2-12/
 
 
-      # - uses: actions/checkout@v2
-      # - name: Run Gradle
-      #   run: |
-      #     echo "./gradlew check --no-daemon --no-scan --parallel"
-      #     ./gradlew check --no-daemon --no-scan --parallel
-      #     GRADLE_CHECK_STATUS=$?
+      - uses: actions/checkout@v2
+      - name: Run Gradle
+        # run: |
+        #   echo "./gradlew check --no-daemon --no-scan --parallel"
+        #   ./gradlew check --no-daemon --no-scan --parallel
+        #   GRADLE_CHECK_STATUS=$?
 
-      #     if [ "$GRADLE_CHECK_STATUS" != 0 ]
-      #     then
-      #       echo Gradle Check Failed!
-      #       exit $GRADLE_CHECK_STATUS
-      #     fi
+        #   if [ "$GRADLE_CHECK_STATUS" != 0 ]
+        #   then
+        #     echo Gradle Check Failed!
+        #     exit $GRADLE_CHECK_STATUS
+        #   fi
+        run: ./gradlew check --parallel
